# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='history_usage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
