# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_auto_20160615_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='up_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 15, 4, 7, 37, 465256, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
